// AUTH
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const CHECK_AUTH = "CHECK_AUTH";

// USER COFFEE
export const ADD_COFFEE_SUCCESS = "ADD_COFFEE_SUCCESS";
export const GET_USERS_COFFEE = "GET_USERS_COFFEE";
export const GET_COFFEE = "GET_COFFEE";
export const GET_COFFEE_TASTINGS = "GET_COFFEE_TASTINGS";
export const GET_COFFEE_TASTING = "GET_COFFEE_TASTING";
export const EDIT_COFFEE_SUCCESS = "EDIT_COFFEE_SUCCESS";
export const DELETE_COFFEE_SUCCESS = "DELETE_COFFEE_SUCCESS";

export const EDIT_TASTING_SUCCESS = "EDIT_TASTING_SUCCESS";
export const DELETE_TASTING_SUCCESS = "DELETE_TASTING_SUCCESS";

// TASTING
export const GET_TASTING_NOTES_SUCCESS = "GET_TASTING_NOTES_SUCCESS";
export const ADD_TASTING = "ADD_TASTING";

// FEED
export const GET_ALL_COFFEE = "GET_ALL_COFFEE";

// USER
export const GET_USERS = "GET_USERS";
